[global_tags]
  # Configuration for tags that are added globally

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = ""

[[outputs.file]]
  files = ["stdout", "/tmp/metrics.out"]
  data_format = "influx"

[[inputs.mqtt_consumer]]
  servers = ["tcp://192.168.0.101:1883"]  # Replace with your MQTT broker address and port
  topics = [
    "sensor/ESP1",
    "sensor/ESP2",
    # "esp2/temperature",
    # "esp2/humidity",
    # Add more topics as needed for other devices
  ]
  qos = 0  # Quality of Service level (0 = at most once, 1 = at least once, 2 = exactly once)
  connection_timeout = "30s"  # Timeout for connection to the broker
  persistent_session = false  # Whether to use a persistent session
  client_id = ""  # Client ID for the MQTT connection
  username = ""  # Username for authentication (if required)
  password = ""  # Password for authentication (if required)

  # Data format configuration
  data_format = "json"

# [[outputs.influxdb]]
#   urls = ["http://influxdb:8086"]  # Replace with the address of your InfluxDB instance
#   database = "data"  # Replace with the name of your database
#   username = "adminadmin"       # Replace with your InfluxDB username
#   password = "adminadmin"       # Replace with your InfluxDB password

[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  urls = ["http://192.168.0.101:8086"]

  ## Token for authentication.
  token = "wjA4geny9y1jCQNGM-QdQpC3FbCq8G8IkQ36ZN0USbvBfutZpm94Hliq13fvR_gD7N2sypBxej0LOr1ooeJcVw=="

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "admin"

  ## Destination bucket to write into.
  bucket = "data"



# [[inputs.cpu]]
#   percpu = true
#   totalcpu = true
#   collect_cpu_time = false
#   report_active = false

# [[inputs.mem]]
#   # no configuration

# [[inputs.system]]
#   # no configuration
